# Generated by Django 5.2.8 on 2026-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='action_taken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Flagged', 'Flagged'), ('Escalated', 'Escalated')], default='Active', max_length=20),
        ),
    ]
