# Generated by Django 5.2.8 on 2026-03-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert_action_taken_alert_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='vote_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.voterecord'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
